apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns-rfc2136
type: Opaque
stringData:
  CLOUDFLARE_ZONE_ID: "replace-me"
  CLOUDFLARE_API_TOKEN: "replace-me"
  TSIG_SECRET: "base64-encoded-secret"
